"""
Alembic configuration file.
Tells Alembic where migrations are stored and other settings.
"""

[alembic]
# path to migration scripts
script_location = alembic

# template to use to generate migration file names
file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present
# defaults to the current directory
prepend_sys_path = .

# timezone to use when rendering the date
# within the "create date" field. When set to the string UTC, the generated
# datetime objects will be timezone aware with tzinfo set to a UTC()
# instance. When omitted, the generated datetime will be naive.
sqlalchemy.url = postgresql://complyiq:SecurePass2026!@localhost/complyiq_db
